import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const bodoni = localFont({
  src: [
    {
      path: "../assets/fonts/bodoni-72-book.ttf",
      weight: "400",
    },
  ],
  display: "swap",
  variable: "--font-bodoni",
});

const rethinkSans = localFont({
  src: [
    {
      path: "../assets/fonts/RethinkSans-Regular.ttf",
      weight: "400",
    },
    {
      path: "../assets/fonts/RethinkSans-Bold.ttf",
      weight: "700",
    },
    {
      path: "../assets/fonts/RethinkSans-Medium.ttf",
      weight: "500",
    },
  ],
  display: "swap",
  variable: "--font-rethink-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bodoni.variable} ${rethinkSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
